#!/usr/bin/env python2.6

import os
from subprocess import call

args = [(5e-3, 0.0), (5e-3, 1e-5), (5e-3, 1e-4), (250e-3, 0.0), (250e-3, 1e-5), (250e-3, 1e-4)]

# Run make in the parent directory
os.environ['PATH'] = os.path.abspath("..") + os.environ['PATH']
call(["make", "distclean"])
call(["make"])

# Now run the simulator for each case
for a in args:
  call(["sim", "-S 10000", "-N 1", "-c 5000000",  "-t " + str(a[0]), "-b " + str(a[1])])

data = []

f = open("ABP.dat")

for line in f:
  data.append([float(s) for s in line.split("|")[1].split(" ") if s.strip()])

print(data)

