#!/usr/bin/env python2.6

import os, pickle
from subprocess import call

args = [(5e-3, 0.0), (5e-3, 1e-5), (5e-3, 1e-4), (250e-3, 0.0), (250e-3, 1e-5), (250e-3, 1e-4)]
sim_type = "ABP"
N = 1 if sim_type == "ABP" or sim_type == "ABP_NAK" else 4
nak = ["-n"] if sim_type == "ABP_NAK" else [] 

# Run make in the parent directory
os.chdir(os.path.dirname(os.path.realpath(__file__)) + "/..")
call(["make", "clean"])
call(["make"])

# Now run the simulator for each case
for a in args:
  call(["./sim", "-S 10000", "-N " + str(N), "-t " + str(a[0]), "-b " + str(a[1])] + nak)

data = []

f = open(sim_type+".out")

for line in f:
  data.append([float(s.strip()) for s in line.split("|")[1].split(" ") if s.strip()])

f.close()

f = open(sim_type+".csv", "w")

for i in range(len(data[0])):
  line = ""
  for j in range(len(data)):
    line += str(data[j][i])+","
  line = line.rstrip(",") + "\n"
  f.write(line)

f.close()

f = open(sim_type+".dat", "w")
pickle.dump(data, f, 2)
f.close()

